# Generated by Django 5.1 on 2024-11-06 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ravenloft', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Realm',
            new_name='Domain',
        ),
    ]
