# Generated by Django 5.1 on 2024-11-13 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ravenloft', '0002_rename_realm_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('day_completed', models.PositiveIntegerField(blank=True, null=True)),
                ('day_given', models.PositiveIntegerField()),
                ('given_by', models.CharField(max_length=60)),
                ('notes', models.TextField(blank=True)),
                ('objective', models.CharField()),
                ('reward', models.TextField(blank=True)),
                ('status', models.IntegerField(choices=[(1, 'Not Started'), (2, 'In Progress'), (3, 'Pending Reward'), (4, 'Completed'), (5, 'Failed'), (6, 'Paused'), (7, 'Abandoned')], default=1)),
                ('time_sensitive', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='domain',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
