# Generated by Django 5.1 on 2024-11-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ravenloft', '0003_quest_alter_domain_notes'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='quest',
            constraint=models.CheckConstraint(condition=models.Q(('day_completed__isnull', True), ('day_completed__gte', models.F('day_given')), _connector='OR'), name='if_provided_day_completed_must_be_gte_day_given', violation_error_message='day_completed cannot be before day_given'),
        ),
    ]
