# Generated by Django 5.1 on 2024-11-14 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ravenloft', '0006_session'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-date']},
        ),
    ]
