# Generated by Django 5.1 on 2024-11-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ravenloft', '0007_alter_session_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Npc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('living_status', models.IntegerField(choices=[(1, 'Alive'), (2, 'Dead'), (3, 'Unknown')], default=1)),
                ('appearance', models.TextField(blank=True)),
                ('relationship_to_party', models.IntegerField(choices=[(1, 'Friendly'), (2, 'Neutral'), (3, 'Adversarial'), (4, 'Uncertain')], default=2)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
