# Generated by Django 5.1 on 2024-11-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ravenloft', '0008_npc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='npc',
            options={'ordering': ['name', 'pk']},
        ),
        migrations.AlterField(
            model_name='npc',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
