# Generated by Django 5.1 on 2024-11-15 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ravenloft', '0010_playercharacter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playercharacter',
            name='religion',
        ),
        migrations.AddField(
            model_name='playercharacter',
            name='deities',
            field=models.TextField(blank=True),
        ),
    ]
