# Generated by Django 5.1 on 2024-11-24 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ravenloft', '0012_creature_pet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('relationship_to_party', models.IntegerField(choices=[(1, 'Friendly'), (2, 'Neutral'), (3, 'Adversarial'), (4, 'Uncertain')], default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
