# Generated by Django 5.1 on 2024-11-24 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ravenloft', '0013_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name']},
        ),
    ]
