# Generated by Django 5.1 on 2024-11-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ravenloft', '0015_groupnpc_group_npcs'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='groupnpc',
            constraint=models.UniqueConstraint(fields=('group', 'npc'), name='unique_group_npc', violation_error_message='group npc association already exists'),
        ),
    ]
