# Generated by Django 5.1 on 2024-11-27 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ravenloft', '0016_groupnpc_unique_group_npc'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPlayerCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_member', models.BooleanField(default=True)),
                ('role', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='groupnpc',
            name='unique_group_npc',
        ),
        migrations.AddConstraint(
            model_name='groupnpc',
            constraint=models.UniqueConstraint(fields=('group', 'npc'), name='unique_group_npc'),
        ),
        migrations.AddField(
            model_name='groupplayercharacter',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ravenloft.group'),
        ),
        migrations.AddField(
            model_name='groupplayercharacter',
            name='player_character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ravenloft.playercharacter'),
        ),
        migrations.AddConstraint(
            model_name='groupplayercharacter',
            constraint=models.UniqueConstraint(fields=('group', 'player_character'), name='unique_group_pc'),
        ),
    ]
