# Generated by Django 5.1 on 2024-11-27 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ravenloft', '0017_groupplayercharacter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='player_characters',
            field=models.ManyToManyField(related_name='groups', through='ravenloft.GroupPlayerCharacter', to='ravenloft.playercharacter'),
        ),
    ]
